### ISSUE TITLE
1.19 support?

### ISSUE THREAD

**Issue by Reimnop** [Patbox/FabricPlaceholderAPI#14]
In the latest version of Minecraft, LiteralText are no longer convertible to MutableText, leading to VerifyError. Are there plans to port this mod to 1.19?

**Comment by Patbox** [comment]
Yes, I'm currently working on that actually. It takes little longer, as I'm changing api/fixing some issues and generally extending parsing part of it.

**Comment by Reimnop** [comment]
That's great to hear! Glad to see this project is still being maintained.

**Comment by Patbox** [comment]
I'm using it myself in quite few mods so it would be weird to not update it :p It didn't get update before as I planned this rework and there were no critical bugs/changes required
