### ISSUE TITLE
Missing mod on the docs website

### ISSUE THREAD

**Issue by Reimnop** [Patbox/FabricPlaceholderAPI#15]
I just released a new mod: [Discord4Fabric](https://github.com/Reimnop/Discord4Fabric). It's a mod that links Discord and Minecraft chat and it depends on Placeholder API. Can it be added to the docs?

**Comment by Patbox** [comment]
Feel free to pr these! If your mod adds global placeholders it should go to https://placeholders.pb4.eu/user/mod-placeholders/ if it can display then to https://placeholders.pb4.eu/user/general/ (or both if you both)
