### ISSUE TITLE
Difficulty post-processing PlaceholderAPI-emitted text

### ISSUE THREAD

**Issue by John-Paul-R** [Patbox/FabricPlaceholderAPI#20]
[This set of changes to ParentNode.toText](https://github.com/Patbox/TextPlaceholderAPI/commit/4851688f663202535b3f7b65876c34d6f9d031ef#diff-bf47758a8cf3f0720e34b07f6e70722c40e5e103d433b62fa828dc3225c5df53) has made post-processing text emitted by PlaceholderAPI far more complex that it was in previous versions.

Consider the scenario:

```java
var defaultStyle = Style.EMPTY.withFormatting(Formatting.GRAY, Formatting.ITALIC);
var playerNameText = Text.empty()
    .append(Text.literal("[UnstyledPrefix] "))
    .append(Text.literal("Steve").formatted(Formatting.AQUA));
var expectedMessage =
    Text.empty()
        .append(playerNameText)
        .append(Text.literal(" is now AFK.").setStyle(defaultStyle));

var out = TextNode.convert(expectedMessage).toText(ParserContext.of(), true);
var stringVal = out.toString();
```

Which yields:

```
literal{[UnstyledPrefix] }[siblings=[
    literal{Steve}[style={color=aqua}],
    literal{ is now AFK.}[style={color=gray,italic}]
]]
```

Before this change, the output would have been:

```
empty[siblings=[
    empty[siblings=[
        literal{[UnstyledPrefix] },
        literal{Steve}[style={color=aqua}]
    ]],
    literal{ is now AFK.}[style={color=gray,italic}]
]]
```

While more verbose, this older layout is _far_ simpler to manipulate, as inserted placeholders will always be one self-contained node, in the same shape they were provided. Right now, I'm having trouble doing things like applying styling to all text nodes except for the inserted node.

**Comment by Patbox** [comment]
Well, now with 1.19.1 "flattening" these text is kinda required if you don't want to get constant "server modified" in case of formatting player ones (see Styled Chat). If you want to manipulate them, using TextNodes to do that was intended solution
