### ISSUE TITLE
Why can I not color a players name using luckperms meta?

### ISSUE THREAD

**Issue by KhaozFrost** [Patbox/FabricPlaceholderAPI#35]
I have tried EVERY single player name related placeholder in place of the one below
```
%player:name%
%player:name_visual%
%player:name_unformatted%
%player:displayname%
%player:displayname_visual%
%player:displayname_unformatted%
%styled-nicknames:display_name%
${vanillaDisplayName}
${default}
${name}
```

%luckperms:meta chatcolor%%player:displayname_unformatted%

the luckperms placeholder is meta.chatcolor.<gr:#936ded:#d5c4ff>

the full strings are:
    "display_name": "%luckperms:meta dex_rank%%luckperms:prefix%%luckperms:meta chatcolor%%player:displayname_unformatted%<r>",
      "chat": "<hover:show_text:'     %luckperms:meta chatcolor%%player:name%     \n<white>Player Rank: %luckperms:prefix%\n<white>Dex Rank: %luckperms:meta dex_rank%'><suggest_command:'/msg %player:name% '>${player} <dark_gray>»<r> ${message}",

nothing I've tried actually works to make the gradient work for the display name. (I don't want to use the nickname plugin)

**Comment by arnokeesman** [comment]
the formatting in the meta placeholder cannot escape the placeholder, if you want to color the username, add colors to styles in the styledchat config, for example:
```json
    {
      "require": {
        "type": "permission",
        "permission": "meta.color.red"
      },
      "display_name": "%luckperms:meta dex_rank%%luckperms:prefix%<red>${default}",
      "message_formats": {},
      "formatting": {},
      "emoticons": {}
    }
```
