### ISSUE TITLE
Using directories in the `font` placeholder causes issues

### ISSUE THREAD

**Issue by DBTDerpbox** [Patbox/FabricPlaceholderAPI#42]
if a font file is placed in a folder in a resource pack and not at the root of the fonts folder for said resource pack's namespace, trying to target that font will prevent the text from displaying properly

Example of it functioning properly:

```json
{
  "style_name": "Default",
  "update_tick_time": 20,
  "list_header": [
    "<font:custom_namespace:fontname><color:#fafafa>some text<font:default>\n\n\n\n",
    "<color:#1cf89e>%server:online%<color:#2f4049>/</color>%server:max_players%",
    ""
  ],
  "list_footer": [
    "",
    "<gray>TPS: %server:tps_colored% <dark_gray>| <gray>MSPT: %server:mspt_colored%",
    "<gray>Ping: <color:#ffba26>%player:ping_colored%</color>"
  ],
  "hidden_in_commands": false,
  "legacy_line_joining (Remove once updating!)": true
}
```
![2023-09-15_04 57 36](https://github.com/Patbox/TextPlaceholderAPI/assets/65347035/287d6b29-c6a0-48c2-8254-24d8d675626d)

Example of it breaking:

```json
{
  "style_name": "Default",
  "update_tick_time": 20,
  "list_header": [
    "<font:custom_namespace:fontname/type1><color:#fafafa>some text<font:default>\n\n\n\n",
    "<color:#1cf89e>%server:online%<color:#2f4049>/</color>%server:max_players%",
    ""
  ],
  "list_footer": [
    "",
    "<gray>TPS: %server:tps_colored% <dark_gray>| <gray>MSPT: %server:mspt_colored%",
    "<gray>Ping: <color:#ffba26>%player:ping_colored%</color>"
  ],
  "hidden_in_commands": false,
  "legacy_line_joining (Remove once updating!)": true
}
```
![2023-09-15_04 57 55](https://github.com/Patbox/TextPlaceholderAPI/assets/65347035/19a88b6c-448b-46c3-bcfe-dd10f397434d)

Using StyledPlayerList for this, I assumed TextPlaceholderAPI is whats breaking given this is using its features, sorry if this isn't the right place to report this.

**Comment by Patbox** [comment]
Could you check if that happens when you do `<font:'custom_namespace:fontname/type1'>`

**Comment by DBTDerpbox** [comment]
does seem to work properly, not sure why I didn't think of trying that
