### ISSUE TITLE
The reversed operation of parseText()

### ISSUE THREAD

**Issue by sakurawald** [Patbox/FabricPlaceholderAPI#59]
Now i can use `parser.parseText()` to convert quick-text `string` into `Text`.
I am wondering if there is a way existing to convert `Text` into quick-text `string`.

**Comment by sakurawald** [comment]
This function is not used ofter. For persist the Text instance, there are gson serializer/deserializer provided by mojang.

**Comment by Patbox** [comment]
Myself I would recommend just storing the input instead, as generated one might not match user input at all (for example, gradients couldn't really be reversed, unless a lot of math/checking was used, but even then it can slightly change when I tweak the code).

You can use included WrappedText utility class for that

**Comment by sakurawald** [comment]
> Myself I would recommend just storing the input instead, as generated one might not match user input at all (for example, gradients couldn't really be reversed, unless a lot of math/checking was used, but even then it can slightly change when I tweak the code).
> 
> You can use included WrappedText utility class for that

Okay, thank you <3.
